# Generated by Django 4.2.5 on 2023-11-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.TextField(max_length=15)),
                ('password_usuario', models.TextField(max_length=20)),
            ],
        ),
    ]
