# Generated by Django 4.2.5 on 2023-11-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='año_publicacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
