# Generated by Django 4.2.5 on 2023-11-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_rename_usuario_prestamo_usuario_solicitante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='usuario_solicitante',
            new_name='usuario',
        ),
    ]
